# Generated by Django 2.2.4 on 2019-08-08 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_Fname', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_county', models.CharField(max_length=200)),
                ('customer_mobileNo', models.BigIntegerField(max_length=14)),
                ('customer_email', models.CharField(max_length=20)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
