# Generated by Django 2.2.4 on 2019-08-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_reg',
            name='customer_mobileNo',
            field=models.BigIntegerField(),
        ),
    ]
